---
name: Build Light

on:
  check_suite:
    types: [completed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: smarthall/load-check-conclusion
      id: check
    - uses: smarthall/lifx-buildlight-action
      with:
        lifx-token: ${{ secrets.LIFX_TOKEN }}
        selector: 'id:d073d514e7d3|0'
        status: ${{ steps.check.output.conclusion }}
